# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holeName', models.CharField(max_length=200)),
                ('holePar', models.IntegerField(choices=[(-6, '-6'), (-5, '-5'), (-4, '-4'), (-3, '-3'), (-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GolfClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.CharField(max_length=200)),
                ('clubName9', models.CharField(max_length=200)),
                ('clubEstablished', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GolfCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200)),
                ('golfClub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip2app.GolfClub')),
            ],
        ),
        migrations.CreateModel(
            name='GolfPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('secondName', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('handicap', models.IntegerField(choices=[(-18, '-18'), (-17, '-17'), (-16, '-16'), (-15, '-15'), (-14, '-14'), (-13, '-13'), (-12, '-12'), (-11, '-11'), (-10, '-10'), (-9, '-9'), (-8, '-8'), (-7, '-7'), (-6, '-6'), (-5, '-5'), (-4, '-4'), (-3, '-3'), (-2, '-2'), (-1, '-1'), (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18')])),
            ],
        ),
        migrations.CreateModel(
            name='GolfTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=200)),
                ('teamEstablished', models.DateField()),
                ('isBanned', models.BooleanField(default=False)),
                ('teamClub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip2app.GolfClub')),
            ],
        ),
        migrations.AddField(
            model_name='golfplayer',
            name='golfTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip2app.GolfTeam'),
        ),
        migrations.AddField(
            model_name='coursehole',
            name='golfCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip2app.GolfCourse'),
        ),
    ]
