# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip2app', '0004_teamtournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamtournament',
            name='GolfTeams',
        ),
        migrations.AddField(
            model_name='teamtournament',
            name='GolfTeams',
            field=models.ManyToManyField(to='ip2app.GolfTeam'),
        ),
    ]
