# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip2app', '0005_auto_20190413_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GolfTeamsPlayingMatch', models.ManyToManyField(choices=[(models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip2app.TeamTournament'), 'test')], to='ip2app.GolfTeam')),
                ('teamTournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip2app.TeamTournament')),
            ],
        ),
    ]
