# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-09 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip2app', '0006_teammatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtournament',
            name='slug',
            field=models.SlugField(default='empty'),
            preserve_default=False,
        ),
    ]
