# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip2app', '0007_teamtournament_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfteam',
            name='slug',
            field=models.SlugField(default='---'),
            preserve_default=False,
        ),
    ]
